Product.destroy_all
Type.destroy_all
Application.destroy_all
Category.destroy_all

t1 = Type.create!(name: 'Глухие')
t2 = Type.create!(name: 'Штабелируемые')
t3 = Type.create!(name: 'Вкладываемые')
t4 = Type.create!(name: 'Решетчатые')
t5 = Type.create!(name: 'Перфорированные')
t6 = Type.create!(name: 'Крышки')

a1 = Application.create!(name: 'Колбасно-мясное производство')
a2 = Application.create!(name: 'Птицефабрики')
a3 = Application.create!(name: 'Хранение овощей')
a4 = Application.create!(name: 'Рыбное производство')
a5 = Application.create!(name: 'Молочное производство')
a6 = Application.create!(name: 'Прочее')

c1 = Category.create!(name: 'Ящики', icon: 'box_menu.png')
c2 = Category.create!(name: 'Складские системы', icon: 'storage_menu.png')
c3 = Category.create!(name: 'Паллеты и кубоконтейнеры', icon: 'pallet_menu.png')
c4 = Category.create!(name: 'Мусорные контейнеры', icon: 'dumpster_menu.png')
c5 = Category.create!(name: 'Сопутствующие товары', icon: 'cart_menu.png')

s1 = 'глухие'
s2 = 'перфорированные'

b1 = 'глухое'
b2 = 'перфорированное'

Product.create!([{
	name: "МОТ Milano",
	category: c2,
	color: "red,blue",
	length: 350,
	width: 230,
	height: 150,
	# diameter: ,
	inner_length: 265,
	inner_width: 206,
	inner_height: 140,
	# inner_diameter: ,
	volume: 12,
	# net_volume: ,
	weight: 0.53,
	side: s1,
	bottom: b1,
	types: [t1, t2],
	cover: false,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: false,
	# var_color_price_1: ,
	# var_color_price_2: ,
	# var_color_price_3: ,
	var_high: true,
	var_high_price_1: 129,
	var_high_price_2: 114,
	var_high_price_3: 109,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	# applications: [a],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},

{
	name: "МОТ Neapol",
	category: c2,
	color: "red,blue",
	length: 400,
	width: 230,
	height: 200,
	# diameter: ,
	inner_length: 300,
	inner_width: 206,
	inner_height: 187,
	# inner_diameter: ,
	volume: 18,
	# net_volume: ,
	weight: 0.73,
	side: s1,
	bottom: b1,
	types: [t1, t2],
	cover: false,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: false,
	# var_color_price_1: ,
	# var_color_price_2: ,
	# var_color_price_3: ,
	var_high: true,
	var_high_price_1: 170,
	var_high_price_2: 160,
	var_high_price_3: 150,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	# applications: [a],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},

{
	name: "МОТ Palermo",
	category: c2,
	color: "red,blue",
	length: 500,
	width: 310,
	height: 200,
	# diameter: ,
	inner_length: 400,
	inner_width: 285,
	inner_height: 187,
	# inner_diameter: ,
	volume: 31,
	# net_volume: ,
	weight: 1.03,
	side: s1,
	bottom: b1,
	types: [t1, t2],
	cover: false,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: false,
	# var_color_price_1: ,
	# var_color_price_2: ,
	# var_color_price_3: ,
	var_high: true,
	var_high_price_1: 258,
	var_high_price_2: 238,
	var_high_price_3: 228,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	# applications: [a],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},

{
	name: "Тележка",
	category: c5,
	color: "red,green,blue",
	length: 627,
	width: 420,
	height: 175,
	# diameter: ,
	# inner_length: ,
	# inner_width: ,
	# inner_height: ,
	# inner_diameter: ,
	# volume: ,
	# net_volume: ,
	weight: 5.8,
	# side: "",
	# bottom: "",
	# types: [t],
	# cover: false,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: false,
	# var_color_price_1: ,
	# var_color_price_2: ,
	# var_color_price_3: ,
	var_high: true,
	var_high_price_1: 1740,
	var_high_price_2: 1607,
	var_high_price_3: 1540,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	# applications: [a],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},

{
	name: "Ящик №15",
	category: c1,
	color: "red,green,blue,white,yellow",
	length: 600,
	width: 400,
	height: 140,
	# diameter: ,
	inner_length: 545,
	inner_width: 350,
	inner_height: 135,
	# inner_diameter: ,
	volume: 26,
	# net_volume: ,
	weight: 1.88,
	side: s1,
	bottom: b1,
	types: [t1, t3],
	cover: true,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "<p>Ящик пластиковый глухой с крышкой для транспортировки, хранения и охлаждения мясной,молочной, рыбной продукции. Выступающий кант по всему периметру крышки обеспечивает возможность формировать прочный штабель при установке ящиков в заполненном виде в несколько ярусов.</p>",
	var_color: true,
	var_color_price_1: 309,
	var_color_price_2: 295,
	var_color_price_3: 281,
	var_high: true,
	var_high_price_1: 427,
	var_high_price_2: 407,
	var_high_price_3: 388,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a4],
	# articul: "",
	position: 13,
	featured: false,
	# campaign: ,
},

=begin
{
	name: "Ящик-корзина №16",
	category: с1,
	color: "red,green,blue,white",
	length: 505,
	width: 295,
	height: 180,
	# diameter: ,
	inner_length: 460,
	inner_width: 270,
	inner_height: 120,
	# inner_diameter: ,
	volume: 15,
	# net_volume: ,
	weight: 0.8,
	side: s2,
	bottom: b2,
	types: [t2, t5],
	cover: false,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: true,
	var_color_price_1: ,
	var_color_price_2: ,
	var_color_price_3: ,
	var_high: true,
	var_high_price_1: ,
	var_high_price_2: ,
	var_high_price_3: ,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a3],
	# articul: "",
	position: 14,
	featured: false,
	# campaign: ,
},
=end


{
	name: "Ящик №17",
	category: c1,
	color: "red,green,blue,white",
	length: 600,
	width: 400,
	height: 250,
	# diameter: ,
	inner_length: 568,
	inner_width: 368,
	inner_height: 242,
	# inner_diameter: ,
	volume: 50,
	# net_volume: ,
	weight: 3.2,
	side: s2,
	bottom: b1,
	types: [t2, t5],
	cover: true,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "<p>Ящик пластиковый для транспортировки, хранения и охлаждения пищевой продукции – колбасных изделий, мясной, рыбной продукции, для транспортировки и складирования непищевой продукции.</p>

	<p>Ящики штабелируются друг на друга в заполненном виде в несколько ярусов, оптимизируя пространство при товародвижении. Особая конструкция дна ящика, а именно выступающий кант по всему периметру ящика, даёт возможность формировать прочный штабель, который крайне устойчив к поперечному смещению.</p>",
	var_color: true,
	var_color_price_1: 374,
	var_color_price_2: 357,
	var_color_price_3: 340,
	var_high: true,
	var_high_price_1: 580,
	var_high_price_2: 553,
	var_high_price_3: 527,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a1, a3],
	# articul: "",
	position: 15,
	featured: false,
	# campaign: ,
},

{
	name: "Ящик №17-1",
	category: c1,
	color: "red,green,blue,white",
	length: 600,
	width: 400,
	height: 250,
	# diameter: ,
	inner_length: 565,
	inner_width: 370,
	inner_height: 240,
	# inner_diameter: ,
	volume: 50,
	# net_volume: ,
	weight: 2.6,
	side: s2,
	bottom: b1,
	types: [t2, t5],
	cover: true,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "<p>Ящик пластиковый для транспортировки, хранения и охлаждения пищевой продукции – колбасных изделий, мясной, рыбной продукции, для транспортировки и складирования непищевой продукции.</p>

	<p>Ящики штабелируются друг на друга в заполненном виде в несколько ярусов, оптимизируя пространство при товародвижении. Особая конструкция дна ящика, а именно выступающий кант по всему периметру ящика, даёт возможность формировать прочный штабель, который крайне устойчив к поперечному смещению.Конструктивная особенность ящика позволяет эффективно использовать его для охлаждения продукции в морозильных камерах.</p>",
	var_color: true,
	var_color_price_1: 370,
	var_color_price_2: 353,
	var_color_price_3: 336,
	var_high: true,
	var_high_price_1: 512,
	var_high_price_2: 488,
	var_high_price_3: 465,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a1, a3],
	# articul: "",
	position: 16,
	featured: false,
	# campaign: ,
},

{
	name: "Паллет TR 1208-2",
	category: c3,
	color: "blue,black,grey",
	length: 1200,
	width: 800,
	height: 155,
	# diameter: ,
	# inner_length: ,
	# inner_width: ,
	# inner_height: ,
	# inner_diameter: ,
	# volume: ,
	# net_volume: ,
	weight: 13,
	# side: ,
	bottom: b2,
	types: [t5],
	cover: false,
	static_load: 6000,
	dynamic_load: 1800,
	rack_load: 500,
	# capacity: "",
	# gallery: "",
	description: "<p>Дополнительные опции:
	<ul>
		<li>усиленный паллет (установка 2 или 3 металлических профилей);</li>
		<li>паллет на 9 ножках;</li>
		<li>паллет без бортиков;</li>
		<li>боковые заглушки;</li>
		<li>индивидуальный цвет (при заказе партии паллет от 300 штук);</li>
		<li>нанесение логотипа (литьевой логотип);</li>
	</ul></p>",
	var_color: false,
	# var_color_price_1: ,
	# var_color_price_2: ,
	# var_color_price_3: ,
	var_high: true,
	var_high_price_1: 2813,
	var_high_price_2: 2596,
	var_high_price_3: 2488,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	# applications: [a],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},

{
	name: "Паллет TR 1208-2-2",
	category: c3,
	color: "blue,black,grey",
	length: 1200,
	width: 800,
	height: 155,
	# diameter: ,
	# inner_length: ,
	# inner_width: ,
	# inner_height: ,
	# inner_diameter: ,
	# volume: ,
	# net_volume: ,
	weight: 17.5,
	# side: ,
	bottom: "перфорированное, усиленное",
	types: [t5],
	cover: false,
	static_load: 6000,
	dynamic_load: 1800,
	rack_load: 1500,
	# capacity: "",
	# gallery: "",
	description: "<p>Дополнительные опции:
	<ul>
		<li>усиленный паллет (установка 2 или 3 металлических профилей);</li>
		<li>паллет на 9 ножках;</li>
		<li>паллет без бортиков;</li>
		<li>боковые заглушки;</li>
		<li>индивидуальный цвет (при заказе партии паллет от 300 штук);</li>
		<li>нанесение логотипа (литьевой логотип);</li>
	</ul></p>",
	var_color: false,
	# var_color_price_1: ,
	# var_color_price_2: ,
	# var_color_price_3: ,
	var_high: false,
	# var_high_price_1: ,
	# var_high_price_2: ,
	# var_high_price_3: ,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	# applications: [a],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},

{
	name: "Бак на 30 литров",
	category: c5,
	color: "red,green,blue,white",
	# length: ,
	width: 350,
	height: 190,
	diameter: 370,
	# inner_length: ,
	# inner_width: ,
	# inner_height: ,
	inner_diameter: 310,
	volume: 30,
	# net_volume: ,
	weight: 1.8,
	side: s1,
	bottom: b1,
	types: [t1, t3],
	cover: true,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "<p>Бак конической формы с дисковой крышкой и двумя козырьковыми ручками производится из полиэтилена низкого давления и предназначен для транспортировки и хранения как пищевой, так и химической продукции.</p>

	<p>Продукция сертифицирована: Сертификат РОСС RU.AE88.H00681.</p>

	<p>Широкая горловина обеспечивает удобство фасовки и выгрузки продукции. Козырьковые ручки удобны для ручного перемещения тары. Усиленные стенки и дно обеспечивают прочность бака при транспортировки и эксплуатации.</p>

	<p>Широко применяется для упаковки продуктов лакокрасочной, нефтеперерабатывающей и пищевой промышленности.</p>

	<p>Крышка бака фиксируется по внутреннему замку и по наружному пазу в горловине бака. Двойная фиксация обеспечивает герметичность бака и надежность крепежа крышки при штабелировании и транспортировки.</p>",
	var_color: true,
	var_color_price_1: 284,
	var_color_price_2: 270,
	var_color_price_3: 257,
	var_high: true,
	var_high_price_1: 388,
	var_high_price_2: 371,
	var_high_price_3: 353,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	# applications: [a],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},

{
	name: "Корзина сетчатая",
	category: c5,
	# color: "red,green,blue,white,yellow,black,grey",
	# length: ,
	# width: ,
	height: 300,
	diameter: 450,
	# inner_length: ,
	# inner_width: ,
	# inner_height: ,
	inner_diameter: 310,
	volume: 30,
	# net_volume: ,
	weight: 0.7,
	side: s2,
	bottom: b1,
	types: [t1, t5, t3, t4],
	cover: false,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "<p>Корзина многофункциональная с глухим дном.
	<ul>
		<li>Для хранения и транспортировки рыбной продукции, овощей, фруктов, грибов, дикоросов и т.д.;</li>
		<li>Для бытовых целей;</li>
		<li>Для питомников под посадку кустарников и деревьев.</li>
	</ul></p>",
	var_color: false,
	# var_color_price_1: ,
	# var_color_price_2: ,
	# var_color_price_3: ,
	var_high: false,
	# var_high_price_1: ,
	# var_high_price_2: ,
	# var_high_price_3: ,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	# applications: [a],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},

{
	name: "Мусорный бак 120л",
	category: c4,
	color: "red,green,blue,white,grey",
	length: 560,
	width: 480,
	height: 960,
	# diameter: ,
	# inner_length: ,
	# inner_width: ,
	# inner_height: ,
	# inner_diameter: ,
	volume: 120,
	# net_volume: ,
	weight: 9.5,
	side: s1,
	bottom: b1,
	types: [t1],
	# cover: false,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: false,
	# var_color_price_1: ,
	# var_color_price_2: ,
	# var_color_price_3: ,
	var_high: true,
	var_high_price_1: 2357,
	var_high_price_2: 2176,
	var_high_price_3: 2085,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	# applications: [a],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},

{
	name: "Мусорный бак 140л",
	category: c4,
	color: "red,green,blue,white,grey",
	length: 560,
	width: 480,
	height: 1060,
	# diameter: ,
	# inner_length: ,
	# inner_width: ,
	# inner_height: ,
	# inner_diameter: ,
	volume: 140,
	# net_volume: ,
	weight: 11,
	side: s1,
	bottom: b1,
	types: [t1],
	# cover: false,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: false,
	# var_color_price_1: ,
	# var_color_price_2: ,
	# var_color_price_3: ,
	var_high: true,
	var_high_price_1: 2290,
	var_high_price_2: 2114,
	var_high_price_3: 2026,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	# applications: [a],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},

{
	name: "Мусорный бак 240л",
	category: c4,
	color: "red,green,blue,white,grey",
	length: 580,
	width: 730,
	height: 1060,
	# diameter: ,
	# inner_length: ,
	# inner_width: ,
	# inner_height: ,
	# inner_diameter: ,
	volume: 240,
	# net_volume: ,
	weight: 13.5,
	side: s1,
	bottom: b1,
	types: [t1],
	# cover: false,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: false,
	# var_color_price_1: ,
	# var_color_price_2: ,
	# var_color_price_3: ,
	var_high: true,
	var_high_price_1: 3090,
	var_high_price_2: 2832,
	var_high_price_3: 2733,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	# applications: [a],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},

{
	name: "Лоток №7",
	category: c1,
	color: "blue,white",
	length: 420,
	width: 420,
	height: 160,
	# diameter: ,
	inner_length: 375,
	inner_width: 375,
	inner_height: 150,
	# inner_diameter: ,
	volume: 18,
	# net_volume: ,
	weight: 1.8,
	side: s1,
	bottom: b1,
	types: [t1, t3],
	cover: false,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: false,
	# var_color_price_1: ,
	# var_color_price_2: ,
	# var_color_price_3: ,
	var_high: true,
	var_high_price_1: 374,
	var_high_price_2: 357,
	var_high_price_3: 340,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a1],
	# articul: "",
	position: 9,
	featured: false,
	# campaign: ,
},

=begin
{
	name: "Ящик-корзина №10",
	category: c1,
	color: "red,green,blue,white",
	length: 600,
	width: 400,
	height: 130,
	# diameter: ,
	inner_length: 550,
	inner_width: 365,
	inner_height: 110,
	# inner_diameter: ,
	volume: 18,
	# net_volume: ,
	weight: 1.34,
	side: s2,
	bottom: b2,
	types: [t5, t3, t2],
	cover: false,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: true,
	var_color_price_1: ,
	var_color_price_2: ,
	var_color_price_3: ,
	var_high: true,
	var_high_price_1: ,
	var_high_price_2: ,
	var_high_price_3: ,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a3, a4],
	# articul: "",
	position: 10,
	featured: false,
	# campaign: ,
},
=end


{
	name: "Ящик №11",
	category: c1,
	color: "red,green,blue,white",
	length: 600,
	width: 400,
	height: 200,
	# diameter: ,
	inner_length: 555,
	inner_width: 355,
	inner_height: 180,
	# inner_diameter: ,
	volume: 35,
	# net_volume: ,
	weight: 1.9,
	side: s1,
	bottom: b1,
	types: [t1, t2],
	cover: true,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "<p>Ящик пластиковый глухой для транспортировки, хранения и охлаждения пищевой продукции – мясной, рыбной продукции, кисломолочной продукции, кондитерских и хлебных изделий, сыпучих продуктов.</p>

		<p>Ящики штабелируются друг на друга в заполненном виде в несколько ярусов, оптимизируя пространство при товародвижении. Особая конструкция дна ящика, а именно выступающий кант по всему периметру ящика, даёт возможность формировать прочный штабель, который крайне устойчив к поперечному смещению. Ящик может комплектоваться крышкой. Конструкция крышки обеспечивает возможность формировать прочный штабель при установке ящиков на крышку в несколько ярусов.</p>",
	var_color: true,
	var_color_price_1: 295,
	var_color_price_2: 281,
	var_color_price_3: 268,
	var_high: true,
	var_high_price_1: 405,
	var_high_price_2: 386,
	var_high_price_3: 368,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a1, a2, a3, a5],
	# articul: "",
	position: 11,
	featured: false,
	# campaign: ,
},

{
	name: "Ящик №12",
	category: c1,
	color: "red,green,blue,white",
	length: 600,
	width: 400,
	height: 250,
	# diameter: ,
	inner_length: 555,
	inner_width: 355,
	inner_height: 240,
	# inner_diameter: ,
	volume: 45,
	# net_volume: ,
	weight: 2.18,
	side: s1,
	bottom: b1,
	types: [t1, t2],
	cover: true,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "<p>Ящик пластиковый глухой для транспортировки, хранения и охлаждения пищевой продукции – мясной, рыбной продукции, кисломолочной продукции, кондитерских и хлебных изделий, сыпучих продуктов.</p>

	<p>Ящики штабелируются друг на друга в заполненном виде в несколько ярусов, оптимизируя пространство при товародвижении. Особая конструкция дна ящика, а именно выступающий кант по всему периметру ящика, даёт возможность формировать прочный штабель, который крайне устойчив к поперечному смещению.</p>

	<p>Ящик может комплектоваться крышкой. Конструкция крышки обеспечивает возможность формировать прочный штабель при установке ящиков на крышку в несколько ярусов.</p>",
	var_color: true,
	var_color_price_1: 332,
	var_color_price_2: 317,
	var_color_price_3: 302,
	var_high: true,
	var_high_price_1: 441,
	var_high_price_2: 421,
	var_high_price_3: 401,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a1, a2, a3, a5],
	# articul: "",
	position: 12,
	featured: false,
	# campaign: ,
},

=begin
{
	name: "Ящик-корзина №1",
	category: c1,
	color: "red,green,blue,white",
	length: 600,
	width: 400,
	height: 180,
	# diameter: ,
	inner_length: 540,
	inner_width: 340,
	inner_height: 170,
	# inner_diameter: ,
	volume: 25,
	# net_volume: ,
	weight: 1.3,
	side: s2,
	bottom: b2,
	types: [t2, t3, t5],
	cover: false,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: true,
	var_color_price_1: ,
	var_color_price_2: ,
	var_color_price_3: ,
	var_high: true,
	var_high_price_1: ,
	var_high_price_2: ,
	var_high_price_3: ,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a1, a3],
	# articul: "",
	position: 1,
	featured: false,
	# campaign: ,
},
=end


=begin
{
	name: "Ящик-корзина №2/П",
	category: c1,
	color: "red,green,blue,white,yellow",
	length: 600,
	width: 400,
	height: 200,
	# diameter: ,
	inner_length: 540,
	inner_width: 340,
	inner_height: 195,
	# inner_diameter: ,
	volume: 25,
	# net_volume: ,
	weight: 1.65,
	side: s2,
	bottom: b2,
	types: [t2, t3, t5],
	cover: true,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: true,
	var_color_price_1: ,
	var_color_price_2: ,
	var_color_price_3: ,
	var_high: true,
	var_high_price_1: ,
	var_high_price_2: ,
	var_high_price_3: ,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a1, a3 ,a5],
	# articul: "",
	position: 2,
	featured: false,
	# campaign: ,
},
=end


=begin
{
	name: "Ящик-корзина №2Г",
	category: c1,
	color: "red,green,blue,white",
	length: 600,
	width: 400,
	height: 200,
	# diameter: ,
	inner_length: 540,
	inner_width: 340,
	inner_height: 195,
	# inner_diameter: ,
	volume: 25,
	# net_volume: ,
	weight: 1.65,
	side: s1,
	bottom: b1,
	types: [t1, t2, t3],
	cover: true,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: true,
	var_color_price_1: ,
	var_color_price_2: ,
	var_color_price_3: ,
	var_high: true,
	var_high_price_1: ,
	var_high_price_2: ,
	var_high_price_3: ,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a],
	# articul: "",
	position: 3,
	featured: false,
	# campaign: ,
},
=end

=begin
{
	name: "Ящик-корзина №3",
	category: c1,
	color: "red,green,blue,white",
	length: 600,
	width: 400,
	height: 300,
	# diameter: ,
	inner_length: 510,
	inner_width: 370,
	inner_height: 295,
	# inner_diameter: ,
	volume: 35,
	# net_volume: ,
	weight: 1.98,
	side: s2,
	bottom: b1,
	types: [t2, t3, t5],
	cover: true,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: true,
	var_color_price_1: ,
	var_color_price_2: ,
	var_color_price_3: ,
	var_high: true,
	var_high_price_1: ,
	var_high_price_2: ,
	var_high_price_3: ,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},
=end

{
	name: "Ящик 601",
	category: c1,
	color: "red, blue",
	length: 600,
	width: 400,
	height: 300,
	# diameter: ,
	inner_length: 505,
	inner_width: 365,
	inner_height: 295,
	# inner_diameter: ,
	volume: 52,
	# net_volume: ,
	weight: 2.5,
	side: s1,
	bottom: b1,
	types: [t1, t3],
	cover: true,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: true,
	var_color_price_1: 536,
	var_color_price_2: 495,
	var_color_price_3: 474,
	var_high: true,
	var_high_price_1: 652,
	var_high_price_2: 602,
	var_high_price_3: 577,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a1, a4],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},

{
	name: "Ящик 602",
	category: c1,
	color: "red, blue",
	length: 600,
	width: 400,
	height: 300,
	# diameter: ,
	inner_length: 505,
	inner_width: 365,
	inner_height: 295,
	# inner_diameter: ,
	volume: 52,
	# net_volume: ,
	weight: 2.4,
	side: s2,
	bottom: b1,
	types: [t1, t3, t5],
	cover: true,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: true,
	var_color_price_1: 526,
	var_color_price_2: 485,
	var_color_price_3: 465,
	var_high: true,
	var_high_price_1: 638,
	var_high_price_2: 589,
	var_high_price_3: 564,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a1, a4],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},

{
	name: "Ящик 603",
	category: c1,
	color: "red, blue",
	length: 600,
	width: 400,
	height: 350,
	# diameter: ,
	inner_length: 505,
	inner_width: 365,
	inner_height: 345,
	# inner_diameter: ,
	volume: 63,
	# net_volume: ,
	weight: 2.8,
	side: s1,
	bottom: b1,
	types: [t1, t3],
	cover: true,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: true,
	var_color_price_1: 561,
	var_color_price_2: 518,
	var_color_price_3: 496,
	var_high: true,
	var_high_price_1: 686,
	var_high_price_2: 633,
	var_high_price_3: 607,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a1, a4],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},

{
	name: "Ящик 604",
	category: c1,
	color: "red, blue",
	length: 600,
	width: 400,
	height: 350,
	# diameter: ,
	inner_length: 505,
	inner_width: 365,
	inner_height: 345,
	# inner_diameter: ,
	volume: 53,
	# net_volume: ,
	weight: 2.6,
	side: s2,
	bottom: b1,
	types: [t1, t3, t5],
	cover: true,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: true,
	var_color_price_1: 547,
	var_color_price_2: 505,
	var_color_price_3: 484,
	var_high: true,
	var_high_price_1: 669,
	var_high_price_2: 618,
	var_high_price_3: 592,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a1, a4],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},

{
	name: "Ящик №18",
	category: c1,
	color: "red,green,blue,white",
	length: 600,
	width: 400,
	height: 200,
	# diameter: ,
	inner_length: 560,
	inner_width: 370,
	inner_height: 175,
	# inner_diameter: ,
	volume: 35,
	# net_volume: ,
	weight: 2.5,
	side: s2,
	bottom: b1,
	types: [t2, t5],
	cover: true,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "<p>Ящик пластиковый для транспортировки, хранения и охлаждения пищевой продукции – колбасных изделий, мясной, рыбной продукции, для транспортировки и складирования пищевой и непищевой продукции.</p>

		<p>Ящики штабелируются друг на друга в заполненном виде в несколько ярусов, оптимизируя пространство при товародвижении. Особая конструкция дна ящика, а именно выступающий кант по всему периметру ящика, даёт возможность формировать прочный штабель, который крайне устойчив к поперечному смещению.</p>",
	var_color: true,
	var_color_price_1: 356,
	var_color_price_2: 340,
	var_color_price_3: 324,
	var_high: true,
	var_high_price_1: 507,
	var_high_price_2: 484,
	var_high_price_3: 461,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a1, a2],
	# articul: "",
	position: 17,
	featured: false,
	# campaign: ,
},

{
	name: "Ящик №19",
	category: c1,
	color: "red,green,blue,white",
	length: 660,
	width: 340,
	height: 365,
	# diameter: ,
	inner_length: 635,
	inner_width: 310,
	inner_height: 360,
	# inner_diameter: ,
	volume: 70,
	# net_volume: ,
	weight: 1.97,
	side: s2,
	bottom: b2,
	types: [t2, t5],
	cover: false,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "<p>Ящик пластиковый для транспортировки и хранения яиц в яичной ячейке, а также для хранения и транспортировки хлебной, мясной, рыбной и другой продукции.</p>

	<p>Ящики устойчиво штабелируются друг на друга в заполненном виде в несколько ярусов, оптимизируя пространство при товародвижении. Особая конструкция дна ящика, а именно выступающий кант по всему периметру ящика, даёт возможность формировать прочный штабель, который крайне устойчив к поперечному смещению.</p>",
	var_color: true,
	var_color_price_1: 396,
	var_color_price_2: 378,
	var_color_price_3: 360,
	var_high: true,
	var_high_price_1: 528,
	var_high_price_2: 504,
	var_high_price_3: 480,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a2, a3],
	# articul: "",
	position: 18,
	featured: false,
	# campaign: ,
},

{
	name: "Ящик №22",
	category: c1,
	color: "red,green,blue,white",
	length: 540,
	width: 360,
	height: 135,
	# diameter: ,
	inner_length: 510,
	inner_width: 360,
	inner_height: 135,
	# inner_diameter: ,
	volume: 20,
	# net_volume: ,
	weight: 1.13,
	side: s2,
	bottom: b2,
	types: [t2, t5],
	cover: false,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "<p>Ящик полностью перфорированный. Эта конструктивная особенность позволяет эффективно использовать ящик для охлаждения продукции в морозильных камерах.</p>

	<p>Наличие необходимого количества поперечных ребер жесткости на внешних поверхностях ящика обеспечивают ему прочность.</p>

	<p>Ящик применяется для мясной, рыбной, овощной, кисло-молочной продукции и т.д.</p>",
	var_color: true,
	var_color_price_1: 198,
	var_color_price_2: 189,
	var_color_price_3: 180,
	var_high: true,
	var_high_price_1: 282,
	var_high_price_2: 269,
	var_high_price_3: 256,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a3],
	# articul: "",
	position: 19,
	featured: false,
	# campaign: ,
},

{
	name: "Ящик №23",
	category: c1,
	color: "red,green,blue,white",
	length: 360,
	width: 360,
	height: 170,
	# diameter: ,
	inner_length: 360,
	inner_width: 325,
	inner_height: 165,
	# inner_diameter: ,
	volume: 16,
	# net_volume: ,
	weight: 1.09,
	side: s1,
	bottom: b1,
	types: [t1, t2],
	cover: false,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "<p>Ящик пластиковый для транспортировки, хранения продукции в упаковке «тетрапак», для технических и бытовых целях.</p>

	<p>Ящики штабелируются друг на друга в заполненном виде в несколько ярусов, оптимизируя пространство при товародвижении. Особая конструкция дна ящика, а именно выступающий кант по всему периметру ящика, даёт возможность формировать прочный штабель, который крайне устойчив к поперечному смещению.</p>",
	var_color: true,
	var_color_price_1: 232,
	var_color_price_2: 222,
	var_color_price_3: 211,
	var_high: true,
	var_high_price_1: 287,
	var_high_price_2: 274,
	var_high_price_3: 261,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a1, a5],
	# articul: "",
	position: 20,
	featured: false,
	# campaign: ,
},

=begin
{
	name: "Ящик-корзина №3",
	category: c1,
	color: "red,green,blue,white",
	length: 600,
	width: 400,
	height: 300,
	# diameter: ,
	inner_length: 510,
	inner_width: 370,
	inner_height: 295,
	# inner_diameter: ,
	volume: 35,
	# net_volume: ,
	weight: 1.98,
	side: s1,
	bottom: b1,
	types: [t1, t2, t3],
	cover: true,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: true,
	var_color_price_1: ,
	var_color_price_2: ,
	var_color_price_3: ,
	var_high: true,
	var_high_price_1: ,
	var_high_price_2: ,
	var_high_price_3: ,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a],
	# articul: "",
	position: 5,
	featured: false,
	# campaign: ,
},
=end

=begin
{
	name: "Ящик-корзина №4 «Тетрапак»",
	category: c1,
	color: "red,green,blue,white",
	length: 420,
	width: 340,
	height: 310,
	# diameter: ,
	inner_length: 395,
	inner_width: 315,
	inner_height: 305,
	# inner_diameter: ,
	volume: 36,
	# net_volume: ,
	weight: 1.65,
	side: s2,
	bottom: b2,
	types: [t2, t5],
	cover: false,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	capacity: "20 ячеек",
	# gallery: "",
	description: "",
	var_color: true,
	var_color_price_1: ,
	var_color_price_2: ,
	var_color_price_3: ,
	var_high: true,
	var_high_price_1: ,
	var_high_price_2: ,
	var_high_price_3: ,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a5],
	# articul: "",
	position: 6,
	featured: false,
	# campaign: ,
},
=end

{
	name: "Ящик №5",
	category: c1,
	color: "red,green,blue,white",
	length: 540,
	width: 400,
	height: 310,
	# diameter: ,
	inner_length: 475,
	inner_width: 350,
	inner_height: 135,
	# inner_diameter: ,
	volume: 22,
	# net_volume: ,
	weight: 1.6,
	side: s1,
	bottom: b1,
	types: [t1, t3],
	cover: true,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "<p>Ящик пластиковый глухой для транспортировки, хранения и охлаждения сырково - творожной продукции, копчёностей, кондитерских изделий.</p>",
	var_color: true,
	var_color_price_1: 210,
	var_color_price_2: 200,
	var_color_price_3: 185,
	var_high: true,
	var_high_price_1: 310,
	var_high_price_2: 300,
	var_high_price_3: 285,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a4, a5],
	# articul: "",
	position: 7,
	featured: false,
	# campaign: ,
},

{
	name: "Ящик №6 «Полипак»",
	category: c1,
	color: "red,green,blue,white",
	length: 420,
	width: 340,
	height: 280,
	# diameter: ,
	inner_length: 395,
	inner_width: 320,
	inner_height: 270,
	# inner_diameter: ,
	volume: 34,
	# net_volume: ,
	weight: 2,
	side: s1,
	bottom: b1,
	types: [t1, t2],
	cover: false,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "<p>Ящик пластиковый глухой для транспортировки, хранения продукции в упаковке «тетрапак», «полипак»; сыпучих продуктов; для технических и бытовых целей.</p>

	<p>Ящики штабелируются друг на друга в заполненном виде в несколько ярусов, оптимизируя пространство при товародвижении. Особая конструкция дна ящика, а именно выступающий кант по всему периметру ящика, даёт возможность формировать прочный штабель, который крайне устойчив к поперечному смещению. Глухое дно позволяет, в случае разрыва упаковки с продукцией, не загрязнять транспортное средство и складское помещение.</p>

	<p>При транспортировки пустой тары складируются «тройками».</p>",
	var_color: true,
	var_color_price_1: 293,
	var_color_price_2: 279,
	var_color_price_3: 266,
	var_high: true,
	var_high_price_1: 448,
	var_high_price_2: 427,
	var_high_price_3: 407,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a5],
	# articul: "",
	position: 8,
	featured: false,
	# campaign: ,
},

{
	name: "Ящик №24",
	category: c1,
	color: "red,green,blue,white",
	length: 600,
	width: 400,
	height: 300,
	# diameter: ,
	inner_length: 575,
	inner_width: 380,
	inner_height: 300,
	# inner_diameter: ,
	volume: 65.5,
	# net_volume: ,
	weight: 2.75,
	side: s2,
	bottom: b1,
	types: [t2, t5],
	cover: true,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "<p>Ящик пластиковый для транспортировки, хранения и охлаждения пищевой продукции – колбасных изделий, мясной, рыбной продукции, для транспортировки и складирования непищевой продукции.</p>

		<p>Ящики штабелируются друг на друга в заполненном виде в несколько ярусов, оптимизируя пространство при товародвижении. Особая конструкция дна ящика, а именно выступающий кант по всему периметру ящика, даёт возможность формировать прочный штабель, который крайне устойчив к поперечному смещению.</p>",
	var_color: true,
	var_color_price_1: 499,
	var_color_price_2: 477,
	var_color_price_3: 454,
	var_high: true,
	var_high_price_1: 637,
	var_high_price_2: 608,
	var_high_price_3: 579,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a1, a3],
	# articul: "",
	position: 21,
	featured: false,
	# campaign: ,
},

=begin
{
	name: "Ящик-корзина №2Е",
	category: c1,
	color: "red,green,blue,white,black",
	length: 600,
	width: 400,
	height: 200,
	# diameter: ,
	inner_length: 568,
	inner_width: 368,
	inner_height: 193,
	# inner_diameter: ,
	volume: 40,
	# net_volume: ,
	weight: 2,
	side: s1,
	bottom: b1,
	types: [t1, t2, t3],
	cover: true,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: true,
	var_color_price_1: ,
	var_color_price_2: ,
	var_color_price_3: ,
	var_high: true,
	var_high_price_1: ,
	var_high_price_2: ,
	var_high_price_3: ,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a1, a3, a5],
	# articul: "",
	position: 3,
	featured: false,
	# campaign: ,
},
=end

{
	name: "Контейнер МОТ-10",
	category: c2,
	color: "red,green,blue,white",
	length: 240,
	width: 195,
	height: 80,
	# diameter: ,
	inner_length: 205,
	inner_width: 155,
	inner_height: 75,
	# inner_diameter: ,
	volume: 1,
	# net_volume: ,
	weight: 0.28,
	side: s1,
	bottom: b1,
	types: [t1, t3],
	cover: false,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "<p>Контейнеры изготавливаются из ударопрочного полистирола. Предназначен для хранения мелких комплектующих изделий.</p>

	<p>Универсальная конструкция ящика идеально подходит для использования его для оформления витрин торговых залов, стеллажей складских помещений и т. д.</p>",
	var_color: false,
	# var_color_price_1: ,
	# var_color_price_2: ,
	# var_color_price_3: ,
	var_high: true,
	var_high_price_1: 128,
	var_high_price_2: 121,
	var_high_price_3: 115,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	# applications: [a],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},

{
	name: "Контейнер МОТ-15",
	category: c2,
	color: "red,green,blue,white",
	length: 380,
	width: 220,
	height: 170,
	# diameter: ,
	inner_length: 330,
	inner_width: 160,
	inner_height: 160,
	# inner_diameter: ,
	volume: 7,
	# net_volume: ,
	weight: 0.9,
	side: s1,
	bottom: b1,
	types: [t1, t3],
	cover: false,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "<p>Контейнеры изготавливаются из ударопрочного полистирола. Предназначен для хранения мелких комплектующих изделий.</p>

	<p>Универсальная конструкция ящика идеально подходит для использования его для оформления витрин торговых залов, стеллажей складских помещений и т.д.</p>",
	var_color: true,
	var_color_price_1: 217,
	var_color_price_2: 207,
	var_color_price_3: 197,
	var_high: true,
	var_high_price_1: 248,
	var_high_price_2: 236,
	var_high_price_3: 225,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	# applications: [a],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},

{
	name: "Ящик 605",
	category: c1,
	color: "red,blue",
	length: 600,
	width: 400,
	height: 400,
	# diameter: ,
	inner_length: 305,
	inner_width: 365,
	inner_height: 395,
	# inner_diameter: ,
	volume: 75,
	# net_volume: ,
	weight: 3,
	side: s1,
	bottom: b1,
	types: [t1, t3],
	cover: true,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: false,
	# var_color_price_1: ,
	# var_color_price_2: ,
	# var_color_price_3: ,
	var_high: false,
	# var_high_price_1: ,
	# var_high_price_2: ,
	# var_high_price_3: ,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a1, a4],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},

{
	name: "Ящик 605-1",
	category: c1,
	color: "red,blue",
	length: 600,
	width: 400,
	height: 415,
	# diameter: ,
	inner_length: 505,
	inner_width: 365,
	inner_height: 395,
	# inner_diameter: ,
	volume: 75,
	# net_volume: ,
	weight: 3.8,
	side: s1,
	bottom: b1,
	types: [t1, t3],
	cover: false,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: true,
	var_color_price_1: 599,
	var_color_price_2: 553,
	var_color_price_3: 530,
	var_high: true,
	var_high_price_1: 730,
	var_high_price_2: 674,
	var_high_price_3: 646,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a1, a4],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},

{
	name: "Ящик 606",
	category: c1,
	color: "red,blue",
	length: 600,
	width: 400,
	height: 400,
	# diameter: ,
	inner_length: 505,
	inner_width: 365,
	inner_height: 395,
	# inner_diameter: ,
	volume: 75,
	# net_volume: ,
	weight: 2.9,
	side: s2,
	bottom: b1,
	types: [t1, t5, t3],
	cover: true,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: false,
	# var_color_price_1: 579,
	# var_color_price_2: 534,
	# var_color_price_3: 512,
	var_high: false,
	# var_high_price_1: 704,
	# var_high_price_2: 650,
	# var_high_price_3: 623,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a1, a4],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},

{
	name: "Ящик 606-1",
	category: c1,
	color: "red,blue",
	length: 600,
	width: 400,
	height: 315,
	# diameter: ,
	inner_length: 505,
	inner_width: 365,
	inner_height: 295,
	# inner_diameter: ,
	volume: 52,
	# net_volume: ,
	weight: 3.3,
	side: s1,
	bottom: b1,
	types: [t1, t3],
	cover: false,
	# static_load: ,
	# dynamic_load: ,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: true,
	var_color_price_1: 579,
	var_color_price_2: 534,
	var_color_price_3: 512,
	var_high: true,
	var_high_price_1: 704,
	var_high_price_2: 650,
	var_high_price_3: 623,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	applications: [a1, a4],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},

{
	name: "Паллет PE 400",
	category: c3,
	color: "blue",
	length: 600,
	width: 400,
	height: 135,
	# diameter: ,
	# inner_length: ,
	# inner_width: ,
	# inner_height: ,
	# inner_diameter: ,
	# volume: ,
	# net_volume: ,
	weight: 1.5,
	# side: ,
	bottom: b2,
	types: [t5],
	# cover: false,
	static_load: 250,
	dynamic_load: 250,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: false,
	# var_color_price_1: ,
	# var_color_price_2: ,
	# var_color_price_3: ,
	var_high: true,
	var_high_price_1: 470,
	var_high_price_2: 434,
	var_high_price_3: 405,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	# applications: [a],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},

{
	name: "Паллет PE 680",
	category: c3,
	color: "green,black,grey",
	length: 800,
	width: 600,
	height: 150,
	# diameter: ,
	# inner_length: ,
	# inner_width: ,
	# inner_height: ,
	# inner_diameter: ,
	# volume: ,
	# net_volume: ,
	weight: 6.5,
	# side: ,
	bottom: b1,
	types: [t1],
	# cover: false,
	static_load: 1000,
	dynamic_load: 500,
	# rack_load: ,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: false,
	# var_color_price_1: ,
	# var_color_price_2: ,
	# var_color_price_3: ,
	var_high: true,
	var_high_price_1: 470,
	var_high_price_2: 434,
	var_high_price_3: 405,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	# applications: [a],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},

{
	name: "Паллет PE 1208-1",
	category: c3,
	color: "blue,black,grey",
	length: 1200,
	width: 800,
	height: 155,
	# diameter: ,
	# inner_length: ,
	# inner_width: ,
	# inner_height: ,
	# inner_diameter: ,
	# volume: ,
	# net_volume: ,
	weight: 13.3,
	# side: ,
	bottom: b1,
	types: [t1],
	# cover: false,
	static_load: 6000,
	dynamic_load: 1800,
	rack_load: 500,
	# capacity: "",
	# gallery: "",
	description: "<p>Дополнительные опции:
	<ul>
		<li>усиленный паллет (установка 2 или 3 металлических профилей);</li>
		<li>паллет на 9 ножках;</li>
		<li>паллет без бортиков;</li>
		<li>боковые заглушки;</li>
		<li>индивидуальный цвет (при заказе партии паллет от 300 штук);</li>
		<li>нанесение логотипа (литьевой логотип);</li>
	</ul></p>",
	var_color: false,
	# var_color_price_1: ,
	# var_color_price_2: ,
	# var_color_price_3: ,
	var_high: true,
	var_high_price_1: 2813,
	var_high_price_2: 2596,
	var_high_price_3: 2488,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	# applications: [a],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
},

{
	name: "Паллет PE 1208-1-1",
	category: c3,
	color: "blue,black,grey",
	length: 1200,
	width: 800,
	height: 155,
	# diameter: ,
	# inner_length: ,
	# inner_width: ,
	# inner_height: ,
	# inner_diameter: ,
	# volume: ,
	# net_volume: ,
	weight: 17.5,
	# side: ,
	bottom: b1,
	types: [t1],
	# cover: false,
	static_load: 6000,
	dynamic_load: 1800,
	rack_load: 500,
	# capacity: "",
	# gallery: "",
	description: "",
	var_color: false,
	# var_color_price_1: ,
	# var_color_price_2: ,
	# var_color_price_3: ,
	var_high: true,
	var_high_price_1: 3203,
	var_high_price_2: 2957,
	var_high_price_3: 2833,
	var_spec: false,
	# var_spec_price_1: ,
	# var_spec_price_2: ,
	# var_spec_price_3: ,
	# applications: [a],
	# articul: "",
	# position: ,
	featured: false,
	# campaign: ,
}

])

p "Created #{Category.count} categories"
p "Created #{Product.count} products"
p "Created #{Type.count} types"
p "Created #{Application.count} applications"